sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 314159
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5fq6SkuX1b22EG4ejs
    access-key-secret: OJlgL5imCDVgMj9IGdwQ5qNo4FCSdy
    bucket-name: xbm-picture
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0